# Generated by Django 6.0.4 on 2026-04-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, help_text="The candidate's portrait for the hero section.", null=True, upload_to='hero/')),
            ],
            options={
                'verbose_name': 'Campaign Settings',
                'verbose_name_plural': 'Campaign Settings',
            },
        ),
    ]
