# Generated by Django 6.0.2 on 2026-04-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campaignsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='excerpt',
            field=models.TextField(blank=True, help_text='A short snippet from the article.'),
        ),
    ]
