# Generated by Django 6.0.2 on 2026-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsarticle_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
