# Generated by Django 6.0.2 on 2026-04-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_campaignvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='constituency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='ward',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
