# Generated by Django 6.0.2 on 2026-04-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_subscriber_zip_code_subscriber_constituency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsettings',
            name='quote_video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL to display next to the quote section (e.g., https://www.youtube.com/watch?v=dQw4w9WgXcQ)'),
        ),
    ]
